[tool.ruff]
line-length = 130


[tool.ruff.lint]
# 1. Enable flake8-bugbear (`B`) rules, in addition to the defaults.
select = ["E4", "E7", "E9", "F", "B"]


[tool.ruff.format]
# 5. Use single quotes in `ruff format`.
quote-style = "single"
docstring-code-format = false